"""empty message

Revision ID: 70045cc45db4
Revises: e8158b08c092
Create Date: 2026-04-01 14:02:46.458213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70045cc45db4'
down_revision = 'e8158b08c092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
